# Basic
title: 哼哼的国
subtitle: 有空，多跟自己聊聊天
description: 哈咯，我叫王哼哼，一名 iOS 开发者。现居深圳，就职于 <a href="https://coding.net">CODING</a>。
welcome_message: 欢迎来到我的国，也没什么能给你的，希望这里的东西你会喜欢~
creator: <a href="https://github.com/wanghengheng">@王哼哼</a>

url: "http://wanghengheng.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange, dark or slate. If you need clear, leave it empty.
cover_color: dark

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# # Navigation buttons in the front page.
# nav:
#     - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
#     # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: wanghengheng
    # duoshuo: wangyuanchuang
    
# Social
social:
    weibo: wangyuanchuang
    github: wanghengheng
    # twitter: onevcat
    # gplus: 107108267983477358170
    mail: wangyuanchuang@qq.com

# Google Analytics
ga:
    id: UA-119752384-1
    host: wanghengheng.com


